app:
 name: Ticket Reservation System
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update
      hibernate.connection.CharSet: utf8
      hibernate.connection.characterEncoding: utf8
      hibernate.connection.useUnicode: true
      globally_quoted_identifiers: true
    properties:
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.show_sql: false
      hibernate.format_sql: false
      hibernate.jdbc.batch_size: 500
      hibernate.order_inserts: true
      hibernate.order_updates: true
  datasource:
    databaseDriverName: com.mysql.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/ticket_reservation_system'
    username: root
    password: root
    maxPool: 25
    maxIdle: 10
    minIdle: 5
server:
  port: 8090
logging:
    level:
        root: INFO
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
        file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
    file: '/home/kripashwar/projects/Ticket_Reservation_System/Ticket-Reservation-System/trs.log'